### ISSUE TITLE
Need rules

### ISSUE THREAD

**Issue by homebugel** [malikshi/open_clash#1]
I need rules game

**Comment by malikshi** [comment]
thank you on your first issues
> I need rules game

which games ?
already set all games port to trafficgames, since i don't know every games port they use

```yaml
script:
  shortcuts:
    allgames: network == 'udp' and dst_port not in [21, 22, 23, 53, 80, 123, 143, 194, 443, 465, 587, 853, 993, 995, 998, 2052, 2053, 2082, 2083, 2086, 2095, 2096, 5222, 5228, 5229, 5230, 8080, 8443, 8880, 8888, 8889]

```
